config/routes.rb
Rails.application.routes.draw do
  get 'map/show'
  resources :players
  resources :crews
  resources :locations
  resources :districts
  resources :characters
  resources :factions
  resources :clocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "map#show"
end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  before_action :set_faction, only: %i[ show edit update destroy ]

  # GET /factions or /factions.json
  def index
    @factions = Faction.all
  end

  # GET /factions/1 or /factions/1.json
  def show
  end

  # GET /factions/new
  def new
    @faction = Faction.new
  end

  # GET /factions/1/edit
  def edit
  end

  # POST /factions or /factions.json
  def create
    @faction = Faction.new(faction_params)

    respond_to do |format|
      if @faction.save
        format.html { redirect_to faction_url(@faction), notice: "Faction was successfully created." }
        format.json { render :show, status: :created, location: @faction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factions/1 or /factions/1.json
  def update
    respond_to do |format|
      if @faction.update(faction_params)
        format.html { redirect_to faction_url(@faction), notice: "Faction was successfully updated." }
        format.json { render :show, status: :ok, location: @faction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1 or /factions/1.json
  def destroy
    @faction.destroy

    respond_to do |format|
      format.html { redirect_to factions_url, notice: "Faction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faction
      @faction = Faction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faction_params
      params.require(:faction).permit(:name, :description, :tier, :hold, :turf, :assets, :quirks, :situation)
    end
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/views/factions/_faction.html.erb
<div id="<%= dom_id faction %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= faction.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= faction.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Tier:</strong>
    <%= faction.tier %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hold:</strong>
    <%= faction.hold %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Turf:</strong>
    <%= faction.turf %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Assets:</strong>
    <%= faction.assets %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quirks:</strong>
    <%= faction.quirks %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Situation:</strong>
    <%= faction.situation %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this faction", faction, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this faction', edit_faction_path(faction), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/factions/_form.html.erb
<%= form_with(model: faction, class: "contents") do |form| %>
  <% if faction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(faction.errors.count, "error") %> prohibited this faction from being saved:</h2>

      <ul>
        <% faction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tier %>
    <%= form.number_field :tier, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hold %>
    <%= form.text_field :hold, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :turf %>
    <%= form.text_field :turf, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :assets %>
    <%= form.text_field :assets, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quirks %>
    <%= form.text_field :quirks, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :situation %>
    <%= form.text_field :situation, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/factions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing faction</h1>

  <%= render "form", faction: @faction %>

  <%= link_to "Show this faction", @faction, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to factions", factions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/factions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Factions</h1>
    <%= link_to 'New faction', new_faction_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="factions" class="min-w-full">
    <%= render @factions %>
  </div>
</div>

app/views/factions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New faction</h1>

  <%= render "form", faction: @faction %>

  <%= link_to 'Back to factions', factions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/factions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @faction %>

    <%= link_to 'Edit this faction', edit_faction_path(@faction), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this faction', faction_path(@faction), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to factions', factions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>