config/routes.rb
Rails.application.routes.draw do
  get 'map/show'
  resources :players
  resources :crews
  resources :locations
  resources :districts
  resources :characters
  resources :factions
  resources :clocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "map#show"
end

app/models/clock.rb
class Clock < ApplicationRecord
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  before_action :set_clock, only: %i[ show edit update destroy ]

  # GET /clocks or /clocks.json
  def index
    @clocks = Clock.all
  end

  # GET /clocks/1 or /clocks/1.json
  def show
  end

  # GET /clocks/new
  def new
    @clock = Clock.new
  end

  # GET /clocks/1/edit
  def edit
  end

  # POST /clocks or /clocks.json
  def create
    @clock = Clock.new(clock_params)

    respond_to do |format|
      if @clock.save
        format.html { redirect_to clock_url(@clock), notice: "Clock was successfully created." }
        format.json { render :show, status: :created, location: @clock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocks/1 or /clocks/1.json
  def update
    respond_to do |format|
      if @clock.update(clock_params)
        format.html { redirect_to clock_url(@clock), notice: "Clock was successfully updated." }
        format.json { render :show, status: :ok, location: @clock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocks/1 or /clocks/1.json
  def destroy
    @clock.destroy

    respond_to do |format|
      format.html { redirect_to clocks_url, notice: "Clock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock
      @clock = Clock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clock_params
      params.require(:clock).permit(:name, :description, :sections, :marked)
    end
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/_clock.html.erb
<div id="<%= dom_id clock %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= clock.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= clock.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sections:</strong>
    <%= clock.sections %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Marked:</strong>
    <%= clock.marked %>
  </p>

  <div data-controller="clockworks"
       data-clockworks-sections-value="<%=clock.sections%>"
       data-clockworks-marked-value="<%=clock.marked%>"
  >
    <svg data-clockworks-target="svg">
    </svg>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this clock", clock, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this clock', edit_clock_path(clock), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/clocks/_form.html.erb
<%= form_with(model: clock, class: "contents") do |form| %>
  <% if clock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(clock.errors.count, "error") %> prohibited this clock from being saved:</h2>

      <ul>
        <% clock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sections %>
    <%= form.number_field :sections, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :marked %>
    <%= form.number_field :marked, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/clocks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing clock</h1>

  <%= render "form", clock: @clock %>

  <%= link_to "Show this clock", @clock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to clocks", clocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clocks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Clocks</h1>
    <%= link_to 'New clock', new_clock_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="clocks" class="min-w-full">
    <%= render @clocks %>
  </div>
</div>

app/views/clocks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New clock</h1>

  <%= render "form", clock: @clock %>

  <%= link_to 'Back to clocks', clocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clocks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @clock %>

    <%= link_to 'Edit this clock', edit_clock_path(@clock), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this clock', clock_path(@clock), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to clocks', clocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>